//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_15
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildComponents
    {
        public int ID { get; set; }
        public Nullable<int> BuildID { get; set; }
        public Nullable<int> ComponentID { get; set; }
    
        public virtual Builds Builds { get; set; }
        public virtual Components Components { get; set; }
    }
}
