//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Components()
        {
            this.BuildComponents = new HashSet<BuildComponents>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string ModelName { get; set; }
        public decimal Price { get; set; }
        public string Socket { get; set; }
        public string FormFactor { get; set; }
        public string RamType { get; set; }
        public Nullable<int> PowerWatt { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildComponents> BuildComponents { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
