//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr_15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBuilderAbazovEntities : DbContext
    {
        public PCBuilderAbazovEntities()
            : base("name=PCBuilderAbazovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildComponents> BuildComponents { get; set; }
        public virtual DbSet<Builds> Builds { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
    }
}
